# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('gpa', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('from_year', models.CharField(blank=True, max_length=200, null=True)),
                ('to_year', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('from_year', models.CharField(max_length=200)),
                ('to_year', models.CharField(max_length=200)),
                ('work_summary', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('languages', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('linkedin_url', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.FileField(null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('technical', models.CharField(max_length=300)),
                ('management', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('summary', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Resume'),
        ),
    ]
