# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('award_summary', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('gpa', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('from_year', models.CharField(blank=True, max_length=200, null=True)),
                ('to_year', models.CharField(blank=True, max_length=200, null=True)),
                ('education_summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('from_year', models.CharField(max_length=200)),
                ('to_year', models.CharField(max_length=200)),
                ('work_summary', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('languages', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('linkedin_url', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.FileField(null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('skills', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume')),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.Resume', unique=True)),
                ('theme', models.CharField(choices=[('Specter', 'Specter'), ('Ross', 'Ross'), ('Donna', 'Donna'), ('Louie', 'Louie')], default='Specter', max_length=60)),
                ('font_size', models.IntegerField(default=11)),
                ('font_family', models.CharField(choices=[('Computer Modern', 'Computer Modern'), ('Sans', 'Sans'), ('Teletype', 'Teletype')], default='Sans', max_length=60)),
                ('horizontal_margins', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('top_margin', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('bottom_margin', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Resume'),
        ),
        migrations.AddField(
            model_name='award',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Resume'),
        ),
    ]
