# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
