# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_personal_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='personal',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
