# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20180319_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
    ]
