# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-11 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20180107_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
