# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20180211_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='from_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='to_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
